# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  #- trigger: ":espanso"
  #  replace: "Hi there!"

#  - trigger: ":aa"
#    replace: "Please create a table in Chinese to analyze the sentence structure below, including the following components: Component, Chinese, English, International Phonetic Alphabet (IPA), Description in Chinese, and a summary of the sentence structure."

  - trigger: ":e"
    replace: "Translate to English:"
  
  - trigger: ":c"
    replace: "Translate to Chinese:"

  - trigger: ":t"
    replace: "Please create a table in Chinese to analyze the sentence structure below, including the following components: Chinese, English, International Phonetic Alphabet (IPA), Description in Chinese, and a summary of the sentence structure."
  
  - trigger: ":T"
    replace: "Please create a table in Chinese to analyze the sentence structure below, including the following components: Chinese, English, International Phonetic Alphabet (IPA), Description in Chinese, and a summary of the sentence structure."
      
#  - trigger: ":a"
#    replace: "Which part of the sentence is the subject complement? Explain in Chinese."

  - trigger: ":ss"
    replace: "The phonetic transcription and pronunciation explanation in Chinese."

  - trigger: ":s"
    replace: "The phonetic transcription in Chinese."

  - trigger: ":m"
    replace: "Correct this English sentence."

  - trigger: ":javadoc"
    replace: "Add javadoc comments to this Java code."

  - trigger: ":z"
    replace: "Analyze the main structure of the sentence and explain it using descriptive explanations in Chinese."
    
  - trigger: ":a"
    replace: "句子分析:."

  - trigger: ":k"
    replace: "<- 這句是什麼英文句型"
#  - trigger: ":l"
#    replace: "Please create a table of Sentence Component Analysis (Chinese Explanation in Parentheses), International Phonetic Alphabet (IPA) (Chinese Explanation in Parentheses), Detailed Explanation of Sentence Grammar Structure (Chinese Explanation in Parentheses):"
#    replace: "Please create a table of Sentence Component Analysis (Chinese Explanation in Parentheses), International Phonetic Alphabet (IPA) (Chinese Explanation in Parentheses), Detailed Explanation of Sentence Grammar Structure (Chinese Explanation in Parentheses):"
#  - trigger: ":s"
#    replace: "Please create a table of vocabulary below, their part of speech, International Phonetic Alphabet (IPA), Traditional Chinese definitions and example sentence in both English and Chinese (mark the vocabulary in bold font in the sentence): "
#    replace: "Please create a table of vocabulary below, their part of speech, International Phonetic Alphabet (IPA), Traditional Chinese definitions and example sentence in both English and Chinese (mark the vocabulary in bold font in the sentence): "
